version: 2

sources:
  - name: raw_data
    database: USER_DB_QUAIL
    schema: RAW
    tables:
      - name: market_prices

  - name: analytics
    database: USER_DB_QUAIL
    schema: ANALYTICS
    tables:
      - name: market_forecast_results